application: d20multitool
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:  
- url: /js
  static_dir: js

- url: /.*
  script: d20multitool.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"